service: aws-ses-email
frameworkVersion: '3'

provider:
  httpApi:
    cors: true
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "ses:*"
          Resource:
            - "*"

functions:
  create:
    handler: handler.createContact
    events:
      - httpApi:
          path: /contact-us
          method: post